batch_size: 1
filepath: H:/My Documents/Backgrounds
out_filepath: H:/My Documents/auto_sorted
external_stylesheets : [options/style_sheet.css]

visual_aa : [[3, 300, 7, 4, 4], [300, 150, 5, 3, 2], [150, 75, 3, 2, 2]]

use_clip : True

variational : False

continue_train : False


visual_aa_args :
    in_size : [224, 224]
    in_channels : 3
    dropout : True
    dropout_val : 0.5
    
beta : 0.01
save_path : ckpts/

epoch_num : 3

clip : False

embedding_method : t-sne

general_manifold_params :

    #n_neighbors : 10
    n_components : 3
   
    
n_clusters : 5
regularize : False

reg_penalty : 0.0001

reg_norm : 2

clip_categories : [moody, sunset, neon, comfy, painting, military, city, geometric, text, vaporwave, tropical, forest, woman, vehicle, anime, sunrise, stars, animal]
