batch_size: 64
filepath: H:/My Documents/Backgrounds
out_filepath: H:/My Documents/auto_sorted
external_stylesheets : [options/style_sheet.css]


use_clip : False
variational : True
continue_train : True
warmup_iters : 3000
reg_penalty : 0.0001
lr : 0.0001
beta : 0.01
epoch_num : 10
regularize : False
reg_norm : 1


visual_aa_args :
    in_size : [256, 256]
    in_channels : 3
    dropout_val : 0.2
save_path : ckpts/


clip_grad : False

embedding_method : t-sne
general_manifold_params :

    #n_neighbors : 10
    n_components : 3
   
n_clusters : 5

clip_categories : [moody, sunset, neon, comfy, painting, military, city, geometric, text, vaporwave, tropical, forest, woman, vehicle, anime, sunrise, stars, animal]
